name: 部署到 GitHub Pages

on:
  push:
    branches:
      - main # 当推送到 main 分支时触发
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取完整的 git 历史记录

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16"
          cache: "npm"

      - name: 安装依赖
        run: npm ci

      - name: 构建项目
        run: npm run build

      - name: 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vuepress/dist
          force_orphan: true
          keep_files: false
          cname: b.Stone.com # 你的自定义域名，如果没有可以删除这行
